services:
  facturatie:
    container_name: facturatie-node
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
    environment:
      - RABBITMQ_USER=user
      - RABBITMQ_PASSWORD=password
      # - RABBITMQ_HOST=10.2.160.51
      - RABBITMQ_HOST=127.0.0.1
    restart: always

  fossbilling:
    image: fossbilling/fossbilling:latest
    restart: always
    ports:
      - "876:80"
    volumes:
      - fossbilling:/var/www/html

  mysql:
    image: mysql:8.2
    restart: always
    environment:
      MYSQL_DATABASE: fossbilling
      MYSQL_USER: fossbilling
      MYSQL_PASSWORD: fossbillingPassword123$
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  fossbilling:
    driver: local
  mysql:
    driver: local
